"""empty message

Revision ID: 3cb447831779
Revises: d957edb6abfa
Create Date: 2021-12-03 11:54:11.857536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb447831779'
down_revision = 'd957edb6abfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'guest', 'state', ['stateid'], ['state_id'])
    op.create_foreign_key(None, 'guest_gift', 'guest', ['guest_id'], ['id'])
    op.create_foreign_key(None, 'guest_gift', 'gift', ['gift_id'], ['id'])
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['state_id'])
    op.create_foreign_key(None, 'question', 'guest', ['guest_id'], ['id'])
    op.add_column('transaction', sa.Column('trx_ipaddress', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'transaction', 'guest', ['trx_guestid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'trx_ipaddress')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'lga', type_='foreignkey')
    op.drop_constraint(None, 'guest_gift', type_='foreignkey')
    op.drop_constraint(None, 'guest_gift', type_='foreignkey')
    op.drop_constraint(None, 'guest', type_='foreignkey')
    # ### end Alembic commands ###
